// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	collectionFieldNames          = builder.RawFieldNames(&Collection{})
	collectionRows                = strings.Join(collectionFieldNames, ",")
	collectionRowsExpectAutoSet   = strings.Join(stringx.Remove(collectionFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	collectionRowsWithPlaceHolder = strings.Join(stringx.Remove(collectionFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheCollectionIdPrefix           = "cache:collection:id:"
	cacheCollectionUidProductIdPrefix = "cache:collection:uid:productId:"
)

type (
	collectionModel interface {
		Insert(ctx context.Context, data *Collection) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Collection, error)
		FindOneByUidProductId(ctx context.Context, uid int64, productId int64) (*Collection, error)
		Update(ctx context.Context, newData *Collection) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCollectionModel struct {
		sqlc.CachedConn
		table string
	}

	Collection struct {
		Id         int64     `db:"id"`          // 收藏Id
		Uid        int64     `db:"uid"`         // 用户id
		ProductId  int64     `db:"product_id"`  // 商品id
		IsDelete   int64     `db:"is_delete"`   // 是否删除
		CreateTime time.Time `db:"create_time"` // 数据创建时间[禁止在代码中赋值]
		UpdateTime time.Time `db:"update_time"` // 数据更新时间[禁止在代码中赋值]
	}
)

func newCollectionModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultCollectionModel {
	return &defaultCollectionModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`collection`",
	}
}

func (m *defaultCollectionModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	collectionIdKey := fmt.Sprintf("%s%v", cacheCollectionIdPrefix, id)
	collectionUidProductIdKey := fmt.Sprintf("%s%v:%v", cacheCollectionUidProductIdPrefix, data.Uid, data.ProductId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, collectionIdKey, collectionUidProductIdKey)
	return err
}

func (m *defaultCollectionModel) FindOne(ctx context.Context, id int64) (*Collection, error) {
	collectionIdKey := fmt.Sprintf("%s%v", cacheCollectionIdPrefix, id)
	var resp Collection
	err := m.QueryRowCtx(ctx, &resp, collectionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", collectionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollectionModel) FindOneByUidProductId(ctx context.Context, uid int64, productId int64) (*Collection, error) {
	collectionUidProductIdKey := fmt.Sprintf("%s%v:%v", cacheCollectionUidProductIdPrefix, uid, productId)
	var resp Collection
	err := m.QueryRowIndexCtx(ctx, &resp, collectionUidProductIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `uid` = ? and `product_id` = ? limit 1", collectionRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, uid, productId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollectionModel) Insert(ctx context.Context, data *Collection) (sql.Result, error) {
	collectionIdKey := fmt.Sprintf("%s%v", cacheCollectionIdPrefix, data.Id)
	collectionUidProductIdKey := fmt.Sprintf("%s%v:%v", cacheCollectionUidProductIdPrefix, data.Uid, data.ProductId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, collectionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Uid, data.ProductId, data.IsDelete)
	}, collectionIdKey, collectionUidProductIdKey)
	return ret, err
}

func (m *defaultCollectionModel) Update(ctx context.Context, newData *Collection) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	collectionIdKey := fmt.Sprintf("%s%v", cacheCollectionIdPrefix, data.Id)
	collectionUidProductIdKey := fmt.Sprintf("%s%v:%v", cacheCollectionUidProductIdPrefix, data.Uid, data.ProductId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, collectionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Uid, newData.ProductId, newData.IsDelete, newData.Id)
	}, collectionIdKey, collectionUidProductIdKey)
	return err
}

func (m *defaultCollectionModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheCollectionIdPrefix, primary)
}

func (m *defaultCollectionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", collectionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCollectionModel) tableName() string {
	return m.table
}
