Name: product.rpc
ListenOn: 127.0.0.1:8081
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc
DataSource: root:123456@tcp(127.0.0.1:3306)/product
CacheRedis:
  - Host: 127.0.0.1:6379
    Pass:
    Type: node
